minimal_mistakes_skin: "default"


title: "Anam Bashir"
title_separator: "-"
name: &name "Anam Bashir"
description: &description "PhD student at UBC researching rental housing in urban Canada."
url: "https://anambashir.github.io"
baseurl: ""
repository: "anambashir/anambashir.github.io"

author:
  avatar: "profile.png"  # Upload a profile picture to /images/
  name: "Anam Bashir"
  pronouns: "she/her"
  bio: "PhD student at UBC | Urban Planning | Housing Justice"
  location: "Vancouver, British Columbia"
  employer: "University of British Columbia"
  email: "anamb@student.ubc.ca"

  # Academic and Professional Profiles
  orcid: "https://orcid.org/0000-0000-XXXX-XXXX"  # Replace with real ORCID
  github: "anambashir"
  linkedin: "anam-bashir-269323140"
  # twitter: "anam_bashir"  # Uncomment if using

social:
  type: Person
  name: Anam Bashir
  links:
    - "https://github.com/anambashir"
    - "https://www.linkedin.com/in/anam-bashir-269323140/"
    # - "https://orcid.org/0000-0000-XXXX-XXXX"
